-- =============================================================================
-- Миграции для ручного применения через Supabase SQL Editor
-- Обновлено 2026-08-10 — книга продаж, QR предоплаты, кодовые слова в Instagram
-- =============================================================================
--
-- ВНИМАНИЕ: этот файл — «пачка что применить сейчас», а не replay истории.
-- Ниже перечислены ФАЙЛЫ миграций в правильном порядке. Открой каждый
-- файл, скопируй его содержимое в SQL Editor и выполни, ЛИБО скачай папку
-- supabase/migrations и запусти `supabase db push` через CLI.
--
-- ПОРЯДОК ПРИМЕНЕНИЯ (важно):
--   1) 20260728120000_excluded_contacts_and_reconciliation.sql   (не был применён)
--   2) 20260730120000_ops_agents_foundation.sql                   (не был применён)
--   3) 20260801120000_rbac_manager_role_and_staff_isolation.sql   (НОВОЕ — RBAC)
--   4) 20260801130000_prepayment_schema.sql                       (НОВОЕ — предоплата)
--   5) 20260801140000_prepayment_receipts_storage.sql             (НОВОЕ — бакет чеков)
--   6) 20260801150000_ai_assistant_rules.sql                      (ai_rules)
--   7) 20260805120000_instagram_channel.sql                       (Instagram Direct)
--   8) 20260807120000_prepayment_hold_in_create_appointment.sql   (НОВОЕ — удержание слота)
--   9) 20260807130000_notify_client_on_hold_expiry.sql            (НОВОЕ — «слот освободился»)
--  10) 20260810120000_sales_playbook_qr_comment_triggers.sql      (НОВОЕ — продажи + QR + Instagram-комментарии)
--
-- ПРО (10): три независимые вещи в одной миграции, все аддитивные.
--   * salon_ai_assistant получает sales_usp / sales_objections / sales_promos /
--     booking_link_mode — «книгу продаж», которую владелец заполняет во вкладке
--     «Ассистент». Пустая книга = поведение ассистента прежнее.
--   * prepayment_settings получает qr_path / qr_url + публичный бакет payment-qr.
--     Требует (4): без prepayment_settings ALTER TABLE упадёт. Салон без QR
--     работает как раньше — реквизиты уходят текстом.
--   * instagram_comment_triggers / instagram_comment_events — кодовое слово под
--     постом → сообщение в директ. Требует (7).
--   Порядок: (10) применять ПОСЛЕ (4) и (7).
--  11) 20260811090000_drop_stale_create_appointment_overload.sql  (ФИКС — обязателен после 8)
--
-- ПРО (11), ВАЖНО: (8) добавила параметр _hold_minutes через CREATE OR REPLACE
-- FUNCTION. В Postgres сигнатура функции включает список аргументов, поэтому
-- добавление параметра НЕ заменяет старую функцию, а создаёт ВТОРУЮ перегрузку
-- рядом. В базе оказались две create_appointment — на 12 и на 13 аргументов.
--
-- Для вызова с ИМЕНОВАННЫМИ аргументами (так делает PostgREST, т.е. вся админка
-- и виджет записи) обе подходят одинаково, и Postgres отказывается выбирать:
--   Could not choose the best candidate function between: ...
-- Вызовы по ПОЗИЦИИ (create_appointment_with_prepayment передаёт все 13) были
-- однозначны всегда — поэтому предоплата работала и маскировала проблему.
--
-- Проявилось не сразу: PostgREST отвечает из кэша схемы. Неоднозначность попала
-- в базу вместе с (8), но кэш ещё помнил одну перегрузку. (10) заканчивается
-- строкой NOTIFY pgrst, 'reload schema' — обычный шаг, чтобы новые таблицы стали
-- видны, — и именно этот перезапуск кэша заставил PostgREST увидеть обе.
--
-- (11) удаляет 12-аргументную версию. 13-аргументная — строгое надмножество
-- (_hold_minutes по умолчанию NULL = прежнее поведение без удержания), поэтому
-- все вызывающие продолжают работать без изменений.
--
-- ЕСЛИ ВИДИТЕ «Could not choose the best candidate function» — применяйте (11).
--
-- Все — идемпотентны (IF NOT EXISTS / OR REPLACE / DROP POLICY IF EXISTS
-- везде). Повторный прогон не ломает данные.
--
-- ЧТОБЫ ЗАРАБОТАЛА ПРЕДОПЛАТА, НУЖНЫ ВСЕ ПЯТЬ: 3, 4, 5, 8, 9 — именно в этом
-- порядке. Нельзя применить только 8 и 9: таблицу prepayment_settings создаёт
-- (4), а функцию user_manager_salon_id, на которую ссылается её RLS-политика,
-- создаёт (3).
--
-- ОСТОРОЖНО, ЭТА ОШИБКА УЖЕ БЫЛА (2026-08-08): применили только 8 и 9, обе
-- прошли «успешно», а админка продолжила писать
--   Could not find the table 'public.prepayment_settings' in the schema cache
-- Причина: тела plpgsql-функций Postgres не проверяет на существование таблиц в
-- момент CREATE, поэтому (8) и (9) спокойно создаются поверх отсутствующей
-- схемы и молчат. Диагностика — что реально есть в базе:
--   SELECT to_regclass('public.prepayment_settings')        AS t_settings,
--          to_regclass('public.appointment_prepayments')    AS t_appt,
--          to_regproc('public.user_manager_salon_id(uuid)') AS fn_rbac;
-- NULL в t_settings = миграция (4) не применена.
--
-- ПОРЯДОК 8 ПОСЛЕ 4 ОБЯЗАТЕЛЕН: (8) удаляет 8-аргументную версию
-- create_appointment_with_prepayment, созданную в (4), и заменяет её обёрткой
-- над create_appointment.
--
-- ЕСЛИ ТАБЛИЦЫ ЕСТЬ, А ОШИБКА ПРО schema cache ОСТАЁТСЯ: это PostgREST с
-- устаревшим кэшем схемы, а не отсутствующая таблица. Лечится одной строкой:
--   NOTIFY pgrst, 'reload schema';
--
-- ЧТО МЕНЯЕТСЯ ДЛЯ САЛОНОВ БЕЗ ПРЕДОПЛАТЫ: ничего. (8) добавляет
-- create_appointment необязательный параметр _hold_minutes; без него поведение
-- побайтово прежнее. Единственное общее изменение — проверка занятости слота
-- теперь считает занятым и активное удержание, а удержания существуют только
-- у салонов, включивших предоплату.
--
-- ROLLBACK новых миграций (порядок обратный):
--   -- Instagram-канал (после отката ассистент в Instagram перестаёт работать,
--   -- WhatsApp не затрагивается):
--   DROP INDEX IF EXISTS public.wa_conversations_channel_idx;
--   DROP INDEX IF EXISTS public.wa_conversations_external_uidx;
--   ALTER TABLE public.wa_conversations DROP CONSTRAINT IF EXISTS wa_conversations_channel_chk;
--   ALTER TABLE public.wa_conversations DROP COLUMN IF EXISTS external_id,
--                                       DROP COLUMN IF EXISTS channel;
--   ALTER TABLE public.salon_secrets DROP COLUMN IF EXISTS instagram_verify_token,
--                                    DROP COLUMN IF EXISTS instagram_app_secret,
--                                    DROP COLUMN IF EXISTS instagram_token,
--                                    DROP COLUMN IF EXISTS instagram_user_id;
--   ALTER TABLE public.salons DROP COLUMN IF EXISTS instagram_enabled;
--   -- ВНИМАНИЕ: строки Instagram-диалогов (client_phone LIKE 'ig:%') после отката
--   -- останутся в wa_conversations без признака канала. При необходимости:
--   --   DELETE FROM public.wa_conversations WHERE client_phone LIKE 'ig:%';
--
--   -- Storage:
--   DELETE FROM storage.buckets WHERE id = 'prepayment-receipts';
--   DROP POLICY IF EXISTS "Salon admin reads own prepayment receipts" ON storage.objects;
--   DROP POLICY IF EXISTS "Manager reads own prepayment receipts"      ON storage.objects;
--
--   -- Prepayment schema:
--   DROP TABLE public.prepayment_audit, public.prepayment_receipt_hashes,
--              public.appointment_prepayments, public.prepayment_settings CASCADE;
--   DROP FUNCTION IF EXISTS public.create_appointment_with_prepayment CASCADE;
--   DROP FUNCTION IF EXISTS public.get_prepayment_by_token CASCADE;
--   DROP FUNCTION IF EXISTS public.prepayment_expire_holds CASCADE;
--   DROP FUNCTION IF EXISTS public.confirm_prepayment CASCADE;
--   SELECT cron.unschedule('prepayment_expire_holds');
--   -- ENUM значения pending_payment / payment_expired остаются (Postgres не
--   -- умеет удалять enum-значения без пересоздания типа); безопасно.
--   ALTER TABLE public.appointments DROP COLUMN IF EXISTS hold_expires_at;
--
--   -- RBAC v2:
--   DROP TABLE public.rbac_audit CASCADE;
--   DROP FUNCTION IF EXISTS public.has_salon_ops_access(uuid, uuid) CASCADE;
--   DROP FUNCTION IF EXISTS public.user_master_ids(uuid) CASCADE;
--   DROP FUNCTION IF EXISTS public.user_manager_salon_id(uuid) CASCADE;
--   DROP POLICY IF EXISTS "Manager reads salon appointments"    ON public.appointments;
--   DROP POLICY IF EXISTS "Manager updates salon appointments"  ON public.appointments;
--   DROP POLICY IF EXISTS "Master reads own appointments"       ON public.appointments;
--   DROP POLICY IF EXISTS "Master updates own appointments"     ON public.appointments;
--   ALTER TABLE public.salons DROP COLUMN IF EXISTS staff_isolation;
--   ALTER TABLE public.masters DROP COLUMN IF EXISTS user_id;
--   -- manager enum-значение остаётся (см. выше). Безопасно.
--
-- ПРОВЕРКА ПОСЛЕ ПРИМЕНЕНИЯ:
--   SELECT EXISTS (SELECT 1 FROM information_schema.columns
--                   WHERE table_name = 'wa_conversations' AND column_name = 'channel')
--                                                           AS ig_channel_col_ok,
--          EXISTS (SELECT 1 FROM information_schema.columns
--                   WHERE table_name = 'salon_secrets' AND column_name = 'instagram_token')
--                                                           AS ig_secrets_ok,
--          to_regclass('public.excluded_contacts')          AS excluded_contacts_ok,
--          to_regclass('public.ops_config')                 AS ops_config_ok,
--          to_regclass('public.prepayment_settings')        AS prepayment_settings_ok,
--          to_regclass('public.appointment_prepayments')    AS prepayment_appt_ok,
--          to_regclass('public.prepayment_receipt_hashes')  AS receipt_hashes_ok,
--          to_regclass('public.rbac_audit')                 AS rbac_audit_ok,
--          to_regclass('public.instagram_comment_triggers') AS ig_triggers_ok,
--          to_regclass('public.instagram_comment_events')   AS ig_comment_events_ok,
--          EXISTS (SELECT 1 FROM information_schema.columns
--                   WHERE table_name = 'salon_ai_assistant' AND column_name = 'sales_usp')
--                                                           AS sales_playbook_ok,
--          EXISTS (SELECT 1 FROM information_schema.columns
--                   WHERE table_name = 'prepayment_settings' AND column_name = 'qr_url')
--                                                           AS prepayment_qr_ok,
--          EXISTS (SELECT 1 FROM storage.buckets WHERE id = 'payment-qr')
--                                                           AS payment_qr_bucket_ok,
--          to_regproc('public.create_appointment_with_prepayment(uuid,uuid,uuid,timestamptz,text,text,text,uuid)')
--                                                           AS prepay_rpc_ok,
--          to_regproc('public.prepayment_expire_holds()')   AS expire_fn_ok,
--          EXISTS (SELECT 1 FROM pg_enum e JOIN pg_type t ON t.oid = e.enumtypid
--                   WHERE t.typname = 'app_role' AND e.enumlabel = 'manager')
--                                                           AS manager_role_ok,
--          EXISTS (SELECT 1 FROM pg_enum e JOIN pg_type t ON t.oid = e.enumtypid
--                   WHERE t.typname = 'appointment_status' AND e.enumlabel = 'pending_payment')
--                                                           AS pending_payment_ok,
--          EXISTS (SELECT 1 FROM information_schema.columns
--                   WHERE table_name = 'salons' AND column_name = 'staff_isolation')
--                                                           AS staff_isolation_col_ok,
--          EXISTS (SELECT 1 FROM information_schema.columns
--                   WHERE table_name = 'masters' AND column_name = 'user_id')
--                                                           AS masters_user_id_ok,
--          (SELECT count(*)::int FROM cron.job
--            WHERE jobname IN ('wa_reconcile_paused_every_minute',
--                              'ops_daily_digest', 'ops_sre_scan_15min',
--                              'prepayment_expire_holds')) AS cron_jobs_scheduled;
--
-- РУЧНАЯ ПРОВЕРКА ПРЕДОПЛАТЫ ПОСЛЕ ПРИМЕНЕНИЯ (сценарий — Instagram Direct):
--   0) СНАЧАЛА на тестовом салоне, НЕ на «Тунукай эже»: включённая предоплата
--      меняет поведение ИИ-Админа для всех новых записей этого салона.
--   1) Админка салона → вкладка «Предоплата»: включи, сумма 200 KGS, удержание
--      30 мин, банк MBANK, номер для перевода. Без номера/карты форма не сохранит.
--   2) Из Instagram напиши боту и дойди до записи. На подтверждении он НЕ должен
--      говорить «записала вас» — только «держу слот до HH:MM», сумма и реквизиты.
--      В БД: appointments.status = pending_payment, hold_expires_at заполнен.
--   3) Второй клиент на то же время получить это окно НЕ должен (слот занят).
--   4) Пришли в тот же чат скриншот чека MBANK на 200 сом → verified,
--      статус записи → confirmed, бот отвечает «Оплата подтверждена».
--   5) Тот же скриншот повторно → отказ (duplicate_file / duplicate_txn).
--   6) Скриншот на меньшую сумму → отказ с причиной «сумма меньше требуемой».
--   7) Не плати 30 минут → статус payment_expired, слот освобождается,
--      и клиенту в Instagram приходит «слот освободился»
--      (cron prepayment_expire_holds → /api/public/prepayment-expired).
--
-- ЕСЛИ ШАГ 7 МОЛЧИТ: уведомление шлёт /api/internal/cron/prepayment-expired.
-- Секрет он берёт из переменной CRON_SECRET, а если её нет — из секрета
-- cron_secret в Supabase Vault (тот же, которым пользуются напоминания и
-- cleanup-wa-media). Настраивать ничего не нужно; если секрета нет и там,
-- эндпоинт ответит 401 и уведомление не уйдёт — слот при этом освободится
-- нормально, это по замыслу. Проверить наличие секрета:
--   SELECT name FROM vault.decrypted_secrets WHERE name = 'cron_secret';
-- (выводит только имя, значение показывать не нужно)
--
-- =============================================================================

-- РУЧНАЯ ПРОВЕРКА INSTAGRAM ПОСЛЕ ПРИМЕНЕНИЯ:
--   1) Админка салона → вкладка «Instagram»: заполни Instagram account ID, Access Token
--      и App Secret, нажми «Сохранить и проверить» — должно показать @username аккаунта.
--   2) В Meta App Dashboard пропиши Callback URL и Verify Token со вкладки, подпишись
--      на поле `messages`. Meta должна принять подписку (GET-хендшейк отвечает challenge).
--   3) Включи переключатель канала вверху вкладки.
--   4) Напиши в Direct с ЛИЧНОГО аккаунта — ассистент должен ответить.
--   5) Доведи до записи: перед подтверждением ассистент обязан спросить номер телефона;
--      после записи проверь, что запись появилась в календаре с этим номером.
--   6) Ответь клиенту вручную из приложения Instagram — ассистент должен замолчать
--      на 5 минут (ai_paused = true у диалога).

-- РУЧНАЯ ПРОВЕРКА КОДОВЫХ СЛОВ В КОММЕНТАРИЯХ (после миграции 10):
--   0) В Meta App Dashboard дополнительно подпишись на поле `comments` (там же, где
--      уже подписано `messages`) и выдай разрешение instagram_business_manage_comments.
--      Без этого вебхук про комментарии просто не придёт — ошибок в логах не будет.
--   1) Админка → вкладка «Instagram» → «Кодовое слово в комментариях»: добавь слово
--      (например ХОЧУ) и текст сообщения, обязательно с вопросом в конце.
--   2) С ЛИЧНОГО аккаунта напиши «ХОЧУ» под любым постом салона → в течение нескольких
--      секунд должно прийти сообщение в директ.
--   3) Напиши то же слово ещё раз под ТЕМ ЖЕ постом → второго сообщения быть НЕ должно
--      (Instagram разрешает один приватный ответ на комментарий).
--   4) Напиши «ХОЧУ» под ДРУГИМ постом, не отвечая на первое сообщение → тоже НЕ должно
--      прийти: правило Meta «одно сообщение, пока человек не ответил» действует на
--      человека, а не на комментарий. В instagram_comment_events будет
--      outcome = skipped_awaiting_reply.
--   5) Ответь в директе → дальше разговор ведёт ассистент, и он НЕ здоровается заново
--      (в state_data диалога лежит entry_context).
--   6) Комментарий без кодового слова → ничего не происходит, outcome = skipped_no_match.

-- РУЧНАЯ ПРОВЕРКА QR ПРЕДОПЛАТЫ (после миграции 10):
--   1) Админка → «Предоплата» → загрузи QR из банковского приложения, сохрани.
--   2) Дойди до записи в WhatsApp: после текста с суммой должен прийти QR картинкой.
--   3) То же в Instagram: QR приходит картинкой, подпись с суммой — отдельным сообщением
--      (в Instagram у картинки не бывает подписи).
--   4) Подтверди запись ещё раз в том же диалоге → второй QR прийти НЕ должен.
--   5) Проверка изоляции: в prepayment_settings.qr_path путь ОБЯЗАН начинаться с id
--      этого салона. Строку с чужим путём ассистент проигнорирует и отправит только
--      текстовые реквизиты (в логах: «prepayment QR path does not belong to salon»).
