-- =============================================================================
-- Миграции для ручного применения через Supabase SQL Editor
-- Обновлено 2026-08-07 — приём чека предоплаты прямо в переписке Instagram
-- =============================================================================
--
-- ВНИМАНИЕ: этот файл — «пачка что применить сейчас», а не replay истории.
-- Ниже перечислены ФАЙЛЫ миграций в правильном порядке. Открой каждый
-- файл, скопируй его содержимое в SQL Editor и выполни, ЛИБО скачай папку
-- supabase/migrations и запусти `supabase db push` через CLI.
--
-- ПОРЯДОК ПРИМЕНЕНИЯ (важно):
--   1) 20260728120000_excluded_contacts_and_reconciliation.sql   (не был применён)
--   2) 20260730120000_ops_agents_foundation.sql                   (не был применён)
--   3) 20260801120000_rbac_manager_role_and_staff_isolation.sql   (НОВОЕ — RBAC)
--   4) 20260801130000_prepayment_schema.sql                       (НОВОЕ — предоплата)
--   5) 20260801140000_prepayment_receipts_storage.sql             (НОВОЕ — бакет чеков)
--   6) 20260801150000_ai_assistant_rules.sql                      (ai_rules)
--   7) 20260805120000_instagram_channel.sql                       (Instagram Direct)
--   8) 20260807120000_prepayment_hold_in_create_appointment.sql   (НОВОЕ — удержание слота)
--   9) 20260807130000_notify_client_on_hold_expiry.sql            (НОВОЕ — «слот освободился»)
--
-- Все — идемпотентны (IF NOT EXISTS / OR REPLACE / DROP POLICY IF EXISTS
-- везде). Повторный прогон не ломает данные.
--
-- ПОРЯДОК 8 ПОСЛЕ 4 ОБЯЗАТЕЛЕН: (8) удаляет 8-аргументную версию
-- create_appointment_with_prepayment, созданную в (4), и заменяет её обёрткой
-- над create_appointment. Если применить (8) раньше (4) — DROP не найдёт что
-- удалять (это не ошибка), но CREATE сошлётся на таблицы предоплаты, которых
-- ещё нет, и упадёт.
--
-- ЧТО МЕНЯЕТСЯ ДЛЯ САЛОНОВ БЕЗ ПРЕДОПЛАТЫ: ничего. (8) добавляет
-- create_appointment необязательный параметр _hold_minutes; без него поведение
-- побайтово прежнее. Единственное общее изменение — проверка занятости слота
-- теперь считает занятым и активное удержание, а удержания существуют только
-- у салонов, включивших предоплату.
--
-- ROLLBACK новых миграций (порядок обратный):
--   -- Instagram-канал (после отката ассистент в Instagram перестаёт работать,
--   -- WhatsApp не затрагивается):
--   DROP INDEX IF EXISTS public.wa_conversations_channel_idx;
--   DROP INDEX IF EXISTS public.wa_conversations_external_uidx;
--   ALTER TABLE public.wa_conversations DROP CONSTRAINT IF EXISTS wa_conversations_channel_chk;
--   ALTER TABLE public.wa_conversations DROP COLUMN IF EXISTS external_id,
--                                       DROP COLUMN IF EXISTS channel;
--   ALTER TABLE public.salon_secrets DROP COLUMN IF EXISTS instagram_verify_token,
--                                    DROP COLUMN IF EXISTS instagram_app_secret,
--                                    DROP COLUMN IF EXISTS instagram_token,
--                                    DROP COLUMN IF EXISTS instagram_user_id;
--   ALTER TABLE public.salons DROP COLUMN IF EXISTS instagram_enabled;
--   -- ВНИМАНИЕ: строки Instagram-диалогов (client_phone LIKE 'ig:%') после отката
--   -- останутся в wa_conversations без признака канала. При необходимости:
--   --   DELETE FROM public.wa_conversations WHERE client_phone LIKE 'ig:%';
--
--   -- Storage:
--   DELETE FROM storage.buckets WHERE id = 'prepayment-receipts';
--   DROP POLICY IF EXISTS "Salon admin reads own prepayment receipts" ON storage.objects;
--   DROP POLICY IF EXISTS "Manager reads own prepayment receipts"      ON storage.objects;
--
--   -- Prepayment schema:
--   DROP TABLE public.prepayment_audit, public.prepayment_receipt_hashes,
--              public.appointment_prepayments, public.prepayment_settings CASCADE;
--   DROP FUNCTION IF EXISTS public.create_appointment_with_prepayment CASCADE;
--   DROP FUNCTION IF EXISTS public.get_prepayment_by_token CASCADE;
--   DROP FUNCTION IF EXISTS public.prepayment_expire_holds CASCADE;
--   DROP FUNCTION IF EXISTS public.confirm_prepayment CASCADE;
--   SELECT cron.unschedule('prepayment_expire_holds');
--   -- ENUM значения pending_payment / payment_expired остаются (Postgres не
--   -- умеет удалять enum-значения без пересоздания типа); безопасно.
--   ALTER TABLE public.appointments DROP COLUMN IF EXISTS hold_expires_at;
--
--   -- RBAC v2:
--   DROP TABLE public.rbac_audit CASCADE;
--   DROP FUNCTION IF EXISTS public.has_salon_ops_access(uuid, uuid) CASCADE;
--   DROP FUNCTION IF EXISTS public.user_master_ids(uuid) CASCADE;
--   DROP FUNCTION IF EXISTS public.user_manager_salon_id(uuid) CASCADE;
--   DROP POLICY IF EXISTS "Manager reads salon appointments"    ON public.appointments;
--   DROP POLICY IF EXISTS "Manager updates salon appointments"  ON public.appointments;
--   DROP POLICY IF EXISTS "Master reads own appointments"       ON public.appointments;
--   DROP POLICY IF EXISTS "Master updates own appointments"     ON public.appointments;
--   ALTER TABLE public.salons DROP COLUMN IF EXISTS staff_isolation;
--   ALTER TABLE public.masters DROP COLUMN IF EXISTS user_id;
--   -- manager enum-значение остаётся (см. выше). Безопасно.
--
-- ПРОВЕРКА ПОСЛЕ ПРИМЕНЕНИЯ:
--   SELECT EXISTS (SELECT 1 FROM information_schema.columns
--                   WHERE table_name = 'wa_conversations' AND column_name = 'channel')
--                                                           AS ig_channel_col_ok,
--          EXISTS (SELECT 1 FROM information_schema.columns
--                   WHERE table_name = 'salon_secrets' AND column_name = 'instagram_token')
--                                                           AS ig_secrets_ok,
--          to_regclass('public.excluded_contacts')          AS excluded_contacts_ok,
--          to_regclass('public.ops_config')                 AS ops_config_ok,
--          to_regclass('public.prepayment_settings')        AS prepayment_settings_ok,
--          to_regclass('public.appointment_prepayments')    AS prepayment_appt_ok,
--          to_regclass('public.prepayment_receipt_hashes')  AS receipt_hashes_ok,
--          to_regclass('public.rbac_audit')                 AS rbac_audit_ok,
--          to_regproc('public.create_appointment_with_prepayment(uuid,uuid,uuid,timestamptz,text,text,text,uuid)')
--                                                           AS prepay_rpc_ok,
--          to_regproc('public.prepayment_expire_holds()')   AS expire_fn_ok,
--          EXISTS (SELECT 1 FROM pg_enum e JOIN pg_type t ON t.oid = e.enumtypid
--                   WHERE t.typname = 'app_role' AND e.enumlabel = 'manager')
--                                                           AS manager_role_ok,
--          EXISTS (SELECT 1 FROM pg_enum e JOIN pg_type t ON t.oid = e.enumtypid
--                   WHERE t.typname = 'appointment_status' AND e.enumlabel = 'pending_payment')
--                                                           AS pending_payment_ok,
--          EXISTS (SELECT 1 FROM information_schema.columns
--                   WHERE table_name = 'salons' AND column_name = 'staff_isolation')
--                                                           AS staff_isolation_col_ok,
--          EXISTS (SELECT 1 FROM information_schema.columns
--                   WHERE table_name = 'masters' AND column_name = 'user_id')
--                                                           AS masters_user_id_ok,
--          (SELECT count(*)::int FROM cron.job
--            WHERE jobname IN ('wa_reconcile_paused_every_minute',
--                              'ops_daily_digest', 'ops_sre_scan_15min',
--                              'prepayment_expire_holds')) AS cron_jobs_scheduled;
--
-- РУЧНАЯ ПРОВЕРКА ПРЕДОПЛАТЫ ПОСЛЕ ПРИМЕНЕНИЯ (сценарий — Instagram Direct):
--   0) СНАЧАЛА на тестовом салоне, НЕ на «Тунукай эже»: включённая предоплата
--      меняет поведение ИИ-Админа для всех новых записей этого салона.
--   1) Админка салона → вкладка «Предоплата»: включи, сумма 200 KGS, удержание
--      30 мин, банк MBANK, номер для перевода. Без номера/карты форма не сохранит.
--   2) Из Instagram напиши боту и дойди до записи. На подтверждении он НЕ должен
--      говорить «записала вас» — только «держу слот до HH:MM», сумма и реквизиты.
--      В БД: appointments.status = pending_payment, hold_expires_at заполнен.
--   3) Второй клиент на то же время получить это окно НЕ должен (слот занят).
--   4) Пришли в тот же чат скриншот чека MBANK на 200 сом → verified,
--      статус записи → confirmed, бот отвечает «Оплата подтверждена».
--   5) Тот же скриншот повторно → отказ (duplicate_file / duplicate_txn).
--   6) Скриншот на меньшую сумму → отказ с причиной «сумма меньше требуемой».
--   7) Не плати 30 минут → статус payment_expired, слот освобождается,
--      и клиенту в Instagram приходит «слот освободился»
--      (cron prepayment_expire_holds → /api/public/prepayment-expired).
--
-- ЕСЛИ ШАГ 7 МОЛЧИТ: эндпоинт берёт секрет из переменной CRON_SECRET, а если её
-- нет — из секрета cron_secret в Supabase Vault (тот же, которым пользуются
-- напоминания и cleanup-wa-media). Настраивать ничего не нужно; если секрета
-- нет и там, эндпоинт ответит 403 и уведомление не уйдёт — слот при этом
-- освободится нормально, это по замыслу. Проверить наличие секрета:
--   SELECT name FROM vault.decrypted_secrets WHERE name = 'cron_secret';
-- (выводит только имя, значение показывать не нужно)
--
-- =============================================================================

-- РУЧНАЯ ПРОВЕРКА INSTAGRAM ПОСЛЕ ПРИМЕНЕНИЯ:
--   1) Админка салона → вкладка «Instagram»: заполни Instagram account ID, Access Token
--      и App Secret, нажми «Сохранить и проверить» — должно показать @username аккаунта.
--   2) В Meta App Dashboard пропиши Callback URL и Verify Token со вкладки, подпишись
--      на поле `messages`. Meta должна принять подписку (GET-хендшейк отвечает challenge).
--   3) Включи переключатель канала вверху вкладки.
--   4) Напиши в Direct с ЛИЧНОГО аккаунта — ассистент должен ответить.
--   5) Доведи до записи: перед подтверждением ассистент обязан спросить номер телефона;
--      после записи проверь, что запись появилась в календаре с этим номером.
--   6) Ответь клиенту вручную из приложения Instagram — ассистент должен замолчать
--      на 5 минут (ai_paused = true у диалога).
