/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as BookSlugRouteImport } from './routes/book.$slug'
import { Route as AdminStatsRouteImport } from './routes/admin/stats'
import { Route as AdminNotificationsRouteImport } from './routes/admin/notifications'
import { Route as AdminCalendarRouteImport } from './routes/admin/calendar'
import { Route as AdminSalonsIndexRouteImport } from './routes/admin/salons/index'
import { Route as PreviewSalonSalonIdRouteImport } from './routes/preview.salon.$salonId'
import { Route as AdminSalonsSalonIdRouteImport } from './routes/admin/salons/$salonId'
import { Route as ApiPublicWaSalonIdRouteImport } from './routes/api/public/wa.$salonId'
import { Route as ApiPublicWaCloudSalonIdRouteImport } from './routes/api/public/wa-cloud.$salonId'

const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const BookSlugRoute = BookSlugRouteImport.update({
  id: '/book/$slug',
  path: '/book/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStatsRoute = AdminStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCalendarRoute = AdminCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSalonsIndexRoute = AdminSalonsIndexRouteImport.update({
  id: '/salons/',
  path: '/salons/',
  getParentRoute: () => AdminRoute,
} as any)
const PreviewSalonSalonIdRoute = PreviewSalonSalonIdRouteImport.update({
  id: '/preview/salon/$salonId',
  path: '/preview/salon/$salonId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSalonsSalonIdRoute = AdminSalonsSalonIdRouteImport.update({
  id: '/salons/$salonId',
  path: '/salons/$salonId',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicWaSalonIdRoute = ApiPublicWaSalonIdRouteImport.update({
  id: '/api/public/wa/$salonId',
  path: '/api/public/wa/$salonId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWaCloudSalonIdRoute = ApiPublicWaCloudSalonIdRouteImport.update({
  id: '/api/public/wa-cloud/$salonId',
  path: '/api/public/wa-cloud/$salonId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/stats': typeof AdminStatsRoute
  '/book/$slug': typeof BookSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/salons/$salonId': typeof AdminSalonsSalonIdRoute
  '/preview/salon/$salonId': typeof PreviewSalonSalonIdRoute
  '/admin/salons/': typeof AdminSalonsIndexRoute
  '/api/public/wa-cloud/$salonId': typeof ApiPublicWaCloudSalonIdRoute
  '/api/public/wa/$salonId': typeof ApiPublicWaSalonIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/stats': typeof AdminStatsRoute
  '/book/$slug': typeof BookSlugRoute
  '/admin': typeof AdminIndexRoute
  '/admin/salons/$salonId': typeof AdminSalonsSalonIdRoute
  '/preview/salon/$salonId': typeof PreviewSalonSalonIdRoute
  '/admin/salons': typeof AdminSalonsIndexRoute
  '/api/public/wa-cloud/$salonId': typeof ApiPublicWaCloudSalonIdRoute
  '/api/public/wa/$salonId': typeof ApiPublicWaSalonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/stats': typeof AdminStatsRoute
  '/book/$slug': typeof BookSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/salons/$salonId': typeof AdminSalonsSalonIdRoute
  '/preview/salon/$salonId': typeof PreviewSalonSalonIdRoute
  '/admin/salons/': typeof AdminSalonsIndexRoute
  '/api/public/wa-cloud/$salonId': typeof ApiPublicWaCloudSalonIdRoute
  '/api/public/wa/$salonId': typeof ApiPublicWaSalonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/privacy'
    | '/admin/calendar'
    | '/admin/notifications'
    | '/admin/stats'
    | '/book/$slug'
    | '/admin/'
    | '/admin/salons/$salonId'
    | '/preview/salon/$salonId'
    | '/admin/salons/'
    | '/api/public/wa-cloud/$salonId'
    | '/api/public/wa/$salonId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/privacy'
    | '/admin/calendar'
    | '/admin/notifications'
    | '/admin/stats'
    | '/book/$slug'
    | '/admin'
    | '/admin/salons/$salonId'
    | '/preview/salon/$salonId'
    | '/admin/salons'
    | '/api/public/wa-cloud/$salonId'
    | '/api/public/wa/$salonId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/privacy'
    | '/admin/calendar'
    | '/admin/notifications'
    | '/admin/stats'
    | '/book/$slug'
    | '/admin/'
    | '/admin/salons/$salonId'
    | '/preview/salon/$salonId'
    | '/admin/salons/'
    | '/api/public/wa-cloud/$salonId'
    | '/api/public/wa/$salonId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  PrivacyRoute: typeof PrivacyRoute
  BookSlugRoute: typeof BookSlugRoute
  PreviewSalonSalonIdRoute: typeof PreviewSalonSalonIdRoute
  ApiPublicWaCloudSalonIdRoute: typeof ApiPublicWaCloudSalonIdRoute
  ApiPublicWaSalonIdRoute: typeof ApiPublicWaSalonIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/book/$slug': {
      id: '/book/$slug'
      path: '/book/$slug'
      fullPath: '/book/$slug'
      preLoaderRoute: typeof BookSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/stats': {
      id: '/admin/stats'
      path: '/stats'
      fullPath: '/admin/stats'
      preLoaderRoute: typeof AdminStatsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/calendar': {
      id: '/admin/calendar'
      path: '/calendar'
      fullPath: '/admin/calendar'
      preLoaderRoute: typeof AdminCalendarRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/salons/': {
      id: '/admin/salons/'
      path: '/salons'
      fullPath: '/admin/salons/'
      preLoaderRoute: typeof AdminSalonsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/preview/salon/$salonId': {
      id: '/preview/salon/$salonId'
      path: '/preview/salon/$salonId'
      fullPath: '/preview/salon/$salonId'
      preLoaderRoute: typeof PreviewSalonSalonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/salons/$salonId': {
      id: '/admin/salons/$salonId'
      path: '/salons/$salonId'
      fullPath: '/admin/salons/$salonId'
      preLoaderRoute: typeof AdminSalonsSalonIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/wa/$salonId': {
      id: '/api/public/wa/$salonId'
      path: '/api/public/wa/$salonId'
      fullPath: '/api/public/wa/$salonId'
      preLoaderRoute: typeof ApiPublicWaSalonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/wa-cloud/$salonId': {
      id: '/api/public/wa-cloud/$salonId'
      path: '/api/public/wa-cloud/$salonId'
      fullPath: '/api/public/wa-cloud/$salonId'
      preLoaderRoute: typeof ApiPublicWaCloudSalonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminCalendarRoute: typeof AdminCalendarRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminStatsRoute: typeof AdminStatsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminSalonsSalonIdRoute: typeof AdminSalonsSalonIdRoute
  AdminSalonsIndexRoute: typeof AdminSalonsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCalendarRoute: AdminCalendarRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminStatsRoute: AdminStatsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminSalonsSalonIdRoute: AdminSalonsSalonIdRoute,
  AdminSalonsIndexRoute: AdminSalonsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  PrivacyRoute: PrivacyRoute,
  BookSlugRoute: BookSlugRoute,
  PreviewSalonSalonIdRoute: PreviewSalonSalonIdRoute,
  ApiPublicWaCloudSalonIdRoute: ApiPublicWaCloudSalonIdRoute,
  ApiPublicWaSalonIdRoute: ApiPublicWaSalonIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
