/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ManageTokenRouteImport } from './routes/manage.$token'
import { Route as CatalogSlugRouteImport } from './routes/catalog.$slug'
import { Route as BookSlugRouteImport } from './routes/book.$slug'
import { Route as AdminStatsRouteImport } from './routes/admin/stats'
import { Route as AdminOpsRouteImport } from './routes/admin/ops'
import { Route as AdminNotificationsRouteImport } from './routes/admin/notifications'
import { Route as AdminErrorsRouteImport } from './routes/admin/errors'
import { Route as AdminCalendarRouteImport } from './routes/admin/calendar'
import { Route as AdminBillingRouteImport } from './routes/admin/billing'
import { Route as AdminAccountRouteImport } from './routes/admin/account'
import { Route as AdminSalonsIndexRouteImport } from './routes/admin/salons/index'
import { Route as PreviewSalonSalonIdRouteImport } from './routes/preview.salon.$salonId'
import { Route as ApiPublicWacloudRouteImport } from './routes/api/public/wacloud'
import { Route as ApiPublicIgRouteImport } from './routes/api/public/ig'
import { Route as ApiInternalTelegramRouteImport } from './routes/api/internal/telegram'
import { Route as AdminSalonsSalonIdRouteImport } from './routes/admin/salons/$salonId'
import { Route as ApiPublicWagupshupTokenRouteImport } from './routes/api/public/wagupshup.$token'
import { Route as ApiPublicWacloudSalonIdRouteImport } from './routes/api/public/wacloud.$salonId'
import { Route as ApiPublicIgSalonIdRouteImport } from './routes/api/public/ig.$salonId'
import { Route as ApiPublicIgOauthCallbackRouteImport } from './routes/api/public/ig-oauth.callback'
import { Route as ApiPublicBillingFreedompayRouteImport } from './routes/api/public/billing.freedompay'
import { Route as ApiInternalCronJobRouteImport } from './routes/api/internal/cron.$job'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ManageTokenRoute = ManageTokenRouteImport.update({
  id: '/manage/$token',
  path: '/manage/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogSlugRoute = CatalogSlugRouteImport.update({
  id: '/catalog/$slug',
  path: '/catalog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BookSlugRoute = BookSlugRouteImport.update({
  id: '/book/$slug',
  path: '/book/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStatsRoute = AdminStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOpsRoute = AdminOpsRouteImport.update({
  id: '/ops',
  path: '/ops',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminErrorsRoute = AdminErrorsRouteImport.update({
  id: '/errors',
  path: '/errors',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCalendarRoute = AdminCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBillingRoute = AdminBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAccountRoute = AdminAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSalonsIndexRoute = AdminSalonsIndexRouteImport.update({
  id: '/salons/',
  path: '/salons/',
  getParentRoute: () => AdminRoute,
} as any)
const PreviewSalonSalonIdRoute = PreviewSalonSalonIdRouteImport.update({
  id: '/preview/salon/$salonId',
  path: '/preview/salon/$salonId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWacloudRoute = ApiPublicWacloudRouteImport.update({
  id: '/api/public/wacloud',
  path: '/api/public/wacloud',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIgRoute = ApiPublicIgRouteImport.update({
  id: '/api/public/ig',
  path: '/api/public/ig',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInternalTelegramRoute = ApiInternalTelegramRouteImport.update({
  id: '/api/internal/telegram',
  path: '/api/internal/telegram',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSalonsSalonIdRoute = AdminSalonsSalonIdRouteImport.update({
  id: '/salons/$salonId',
  path: '/salons/$salonId',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicWagupshupTokenRoute = ApiPublicWagupshupTokenRouteImport.update({
  id: '/api/public/wagupshup/$token',
  path: '/api/public/wagupshup/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWacloudSalonIdRoute = ApiPublicWacloudSalonIdRouteImport.update({
  id: '/$salonId',
  path: '/$salonId',
  getParentRoute: () => ApiPublicWacloudRoute,
} as any)
const ApiPublicIgSalonIdRoute = ApiPublicIgSalonIdRouteImport.update({
  id: '/$salonId',
  path: '/$salonId',
  getParentRoute: () => ApiPublicIgRoute,
} as any)
const ApiPublicIgOauthCallbackRoute =
  ApiPublicIgOauthCallbackRouteImport.update({
    id: '/api/public/ig-oauth/callback',
    path: '/api/public/ig-oauth/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBillingFreedompayRoute =
  ApiPublicBillingFreedompayRouteImport.update({
    id: '/api/public/billing/freedompay',
    path: '/api/public/billing/freedompay',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiInternalCronJobRoute = ApiInternalCronJobRouteImport.update({
  id: '/api/internal/cron/$job',
  path: '/api/internal/cron/$job',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/payments': typeof PaymentsRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin/account': typeof AdminAccountRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/errors': typeof AdminErrorsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/ops': typeof AdminOpsRoute
  '/admin/stats': typeof AdminStatsRoute
  '/book/$slug': typeof BookSlugRoute
  '/catalog/$slug': typeof CatalogSlugRoute
  '/manage/$token': typeof ManageTokenRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/salons/$salonId': typeof AdminSalonsSalonIdRoute
  '/api/internal/telegram': typeof ApiInternalTelegramRoute
  '/api/public/ig': typeof ApiPublicIgRouteWithChildren
  '/api/public/wacloud': typeof ApiPublicWacloudRouteWithChildren
  '/preview/salon/$salonId': typeof PreviewSalonSalonIdRoute
  '/admin/salons/': typeof AdminSalonsIndexRoute
  '/api/internal/cron/$job': typeof ApiInternalCronJobRoute
  '/api/public/billing/freedompay': typeof ApiPublicBillingFreedompayRoute
  '/api/public/ig-oauth/callback': typeof ApiPublicIgOauthCallbackRoute
  '/api/public/ig/$salonId': typeof ApiPublicIgSalonIdRoute
  '/api/public/wacloud/$salonId': typeof ApiPublicWacloudSalonIdRoute
  '/api/public/wagupshup/$token': typeof ApiPublicWagupshupTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/payments': typeof PaymentsRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin/account': typeof AdminAccountRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/errors': typeof AdminErrorsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/ops': typeof AdminOpsRoute
  '/admin/stats': typeof AdminStatsRoute
  '/book/$slug': typeof BookSlugRoute
  '/catalog/$slug': typeof CatalogSlugRoute
  '/manage/$token': typeof ManageTokenRoute
  '/admin': typeof AdminIndexRoute
  '/admin/salons/$salonId': typeof AdminSalonsSalonIdRoute
  '/api/internal/telegram': typeof ApiInternalTelegramRoute
  '/api/public/ig': typeof ApiPublicIgRouteWithChildren
  '/api/public/wacloud': typeof ApiPublicWacloudRouteWithChildren
  '/preview/salon/$salonId': typeof PreviewSalonSalonIdRoute
  '/admin/salons': typeof AdminSalonsIndexRoute
  '/api/internal/cron/$job': typeof ApiInternalCronJobRoute
  '/api/public/billing/freedompay': typeof ApiPublicBillingFreedompayRoute
  '/api/public/ig-oauth/callback': typeof ApiPublicIgOauthCallbackRoute
  '/api/public/ig/$salonId': typeof ApiPublicIgSalonIdRoute
  '/api/public/wacloud/$salonId': typeof ApiPublicWacloudSalonIdRoute
  '/api/public/wagupshup/$token': typeof ApiPublicWagupshupTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/payments': typeof PaymentsRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin/account': typeof AdminAccountRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/errors': typeof AdminErrorsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/ops': typeof AdminOpsRoute
  '/admin/stats': typeof AdminStatsRoute
  '/book/$slug': typeof BookSlugRoute
  '/catalog/$slug': typeof CatalogSlugRoute
  '/manage/$token': typeof ManageTokenRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/salons/$salonId': typeof AdminSalonsSalonIdRoute
  '/api/internal/telegram': typeof ApiInternalTelegramRoute
  '/api/public/ig': typeof ApiPublicIgRouteWithChildren
  '/api/public/wacloud': typeof ApiPublicWacloudRouteWithChildren
  '/preview/salon/$salonId': typeof PreviewSalonSalonIdRoute
  '/admin/salons/': typeof AdminSalonsIndexRoute
  '/api/internal/cron/$job': typeof ApiInternalCronJobRoute
  '/api/public/billing/freedompay': typeof ApiPublicBillingFreedompayRoute
  '/api/public/ig-oauth/callback': typeof ApiPublicIgOauthCallbackRoute
  '/api/public/ig/$salonId': typeof ApiPublicIgSalonIdRoute
  '/api/public/wacloud/$salonId': typeof ApiPublicWacloudSalonIdRoute
  '/api/public/wagupshup/$token': typeof ApiPublicWagupshupTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/onboarding'
    | '/payments'
    | '/pricing'
    | '/privacy'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/terms'
    | '/admin/account'
    | '/admin/billing'
    | '/admin/calendar'
    | '/admin/errors'
    | '/admin/notifications'
    | '/admin/ops'
    | '/admin/stats'
    | '/book/$slug'
    | '/catalog/$slug'
    | '/manage/$token'
    | '/admin/'
    | '/admin/salons/$salonId'
    | '/api/internal/telegram'
    | '/api/public/ig'
    | '/api/public/wacloud'
    | '/preview/salon/$salonId'
    | '/admin/salons/'
    | '/api/internal/cron/$job'
    | '/api/public/billing/freedompay'
    | '/api/public/ig-oauth/callback'
    | '/api/public/ig/$salonId'
    | '/api/public/wacloud/$salonId'
    | '/api/public/wagupshup/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/payments'
    | '/pricing'
    | '/privacy'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/terms'
    | '/admin/account'
    | '/admin/billing'
    | '/admin/calendar'
    | '/admin/errors'
    | '/admin/notifications'
    | '/admin/ops'
    | '/admin/stats'
    | '/book/$slug'
    | '/catalog/$slug'
    | '/manage/$token'
    | '/admin'
    | '/admin/salons/$salonId'
    | '/api/internal/telegram'
    | '/api/public/ig'
    | '/api/public/wacloud'
    | '/preview/salon/$salonId'
    | '/admin/salons'
    | '/api/internal/cron/$job'
    | '/api/public/billing/freedompay'
    | '/api/public/ig-oauth/callback'
    | '/api/public/ig/$salonId'
    | '/api/public/wacloud/$salonId'
    | '/api/public/wagupshup/$token'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/onboarding'
    | '/payments'
    | '/pricing'
    | '/privacy'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/terms'
    | '/admin/account'
    | '/admin/billing'
    | '/admin/calendar'
    | '/admin/errors'
    | '/admin/notifications'
    | '/admin/ops'
    | '/admin/stats'
    | '/book/$slug'
    | '/catalog/$slug'
    | '/manage/$token'
    | '/admin/'
    | '/admin/salons/$salonId'
    | '/api/internal/telegram'
    | '/api/public/ig'
    | '/api/public/wacloud'
    | '/preview/salon/$salonId'
    | '/admin/salons/'
    | '/api/internal/cron/$job'
    | '/api/public/billing/freedompay'
    | '/api/public/ig-oauth/callback'
    | '/api/public/ig/$salonId'
    | '/api/public/wacloud/$salonId'
    | '/api/public/wagupshup/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  OnboardingRoute: typeof OnboardingRoute
  PaymentsRoute: typeof PaymentsRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  BookSlugRoute: typeof BookSlugRoute
  CatalogSlugRoute: typeof CatalogSlugRoute
  ManageTokenRoute: typeof ManageTokenRoute
  ApiInternalTelegramRoute: typeof ApiInternalTelegramRoute
  ApiPublicIgRoute: typeof ApiPublicIgRouteWithChildren
  ApiPublicWacloudRoute: typeof ApiPublicWacloudRouteWithChildren
  PreviewSalonSalonIdRoute: typeof PreviewSalonSalonIdRoute
  ApiInternalCronJobRoute: typeof ApiInternalCronJobRoute
  ApiPublicBillingFreedompayRoute: typeof ApiPublicBillingFreedompayRoute
  ApiPublicIgOauthCallbackRoute: typeof ApiPublicIgOauthCallbackRoute
  ApiPublicWagupshupTokenRoute: typeof ApiPublicWagupshupTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/manage/$token': {
      id: '/manage/$token'
      path: '/manage/$token'
      fullPath: '/manage/$token'
      preLoaderRoute: typeof ManageTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog/$slug': {
      id: '/catalog/$slug'
      path: '/catalog/$slug'
      fullPath: '/catalog/$slug'
      preLoaderRoute: typeof CatalogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$slug': {
      id: '/book/$slug'
      path: '/book/$slug'
      fullPath: '/book/$slug'
      preLoaderRoute: typeof BookSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/stats': {
      id: '/admin/stats'
      path: '/stats'
      fullPath: '/admin/stats'
      preLoaderRoute: typeof AdminStatsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ops': {
      id: '/admin/ops'
      path: '/ops'
      fullPath: '/admin/ops'
      preLoaderRoute: typeof AdminOpsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/errors': {
      id: '/admin/errors'
      path: '/errors'
      fullPath: '/admin/errors'
      preLoaderRoute: typeof AdminErrorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/calendar': {
      id: '/admin/calendar'
      path: '/calendar'
      fullPath: '/admin/calendar'
      preLoaderRoute: typeof AdminCalendarRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/billing': {
      id: '/admin/billing'
      path: '/billing'
      fullPath: '/admin/billing'
      preLoaderRoute: typeof AdminBillingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/account': {
      id: '/admin/account'
      path: '/account'
      fullPath: '/admin/account'
      preLoaderRoute: typeof AdminAccountRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/salons/': {
      id: '/admin/salons/'
      path: '/salons'
      fullPath: '/admin/salons/'
      preLoaderRoute: typeof AdminSalonsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/preview/salon/$salonId': {
      id: '/preview/salon/$salonId'
      path: '/preview/salon/$salonId'
      fullPath: '/preview/salon/$salonId'
      preLoaderRoute: typeof PreviewSalonSalonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/wacloud': {
      id: '/api/public/wacloud'
      path: '/api/public/wacloud'
      fullPath: '/api/public/wacloud'
      preLoaderRoute: typeof ApiPublicWacloudRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ig': {
      id: '/api/public/ig'
      path: '/api/public/ig'
      fullPath: '/api/public/ig'
      preLoaderRoute: typeof ApiPublicIgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/telegram': {
      id: '/api/internal/telegram'
      path: '/api/internal/telegram'
      fullPath: '/api/internal/telegram'
      preLoaderRoute: typeof ApiInternalTelegramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/salons/$salonId': {
      id: '/admin/salons/$salonId'
      path: '/salons/$salonId'
      fullPath: '/admin/salons/$salonId'
      preLoaderRoute: typeof AdminSalonsSalonIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/wagupshup/$token': {
      id: '/api/public/wagupshup/$token'
      path: '/api/public/wagupshup/$token'
      fullPath: '/api/public/wagupshup/$token'
      preLoaderRoute: typeof ApiPublicWagupshupTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/wacloud/$salonId': {
      id: '/api/public/wacloud/$salonId'
      path: '/$salonId'
      fullPath: '/api/public/wacloud/$salonId'
      preLoaderRoute: typeof ApiPublicWacloudSalonIdRouteImport
      parentRoute: typeof ApiPublicWacloudRoute
    }
    '/api/public/ig/$salonId': {
      id: '/api/public/ig/$salonId'
      path: '/$salonId'
      fullPath: '/api/public/ig/$salonId'
      preLoaderRoute: typeof ApiPublicIgSalonIdRouteImport
      parentRoute: typeof ApiPublicIgRoute
    }
    '/api/public/ig-oauth/callback': {
      id: '/api/public/ig-oauth/callback'
      path: '/api/public/ig-oauth/callback'
      fullPath: '/api/public/ig-oauth/callback'
      preLoaderRoute: typeof ApiPublicIgOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/billing/freedompay': {
      id: '/api/public/billing/freedompay'
      path: '/api/public/billing/freedompay'
      fullPath: '/api/public/billing/freedompay'
      preLoaderRoute: typeof ApiPublicBillingFreedompayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/cron/$job': {
      id: '/api/internal/cron/$job'
      path: '/api/internal/cron/$job'
      fullPath: '/api/internal/cron/$job'
      preLoaderRoute: typeof ApiInternalCronJobRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAccountRoute: typeof AdminAccountRoute
  AdminBillingRoute: typeof AdminBillingRoute
  AdminCalendarRoute: typeof AdminCalendarRoute
  AdminErrorsRoute: typeof AdminErrorsRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminOpsRoute: typeof AdminOpsRoute
  AdminStatsRoute: typeof AdminStatsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminSalonsSalonIdRoute: typeof AdminSalonsSalonIdRoute
  AdminSalonsIndexRoute: typeof AdminSalonsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAccountRoute: AdminAccountRoute,
  AdminBillingRoute: AdminBillingRoute,
  AdminCalendarRoute: AdminCalendarRoute,
  AdminErrorsRoute: AdminErrorsRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminOpsRoute: AdminOpsRoute,
  AdminStatsRoute: AdminStatsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminSalonsSalonIdRoute: AdminSalonsSalonIdRoute,
  AdminSalonsIndexRoute: AdminSalonsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ApiPublicIgRouteChildren {
  ApiPublicIgSalonIdRoute: typeof ApiPublicIgSalonIdRoute
}

const ApiPublicIgRouteChildren: ApiPublicIgRouteChildren = {
  ApiPublicIgSalonIdRoute: ApiPublicIgSalonIdRoute,
}

const ApiPublicIgRouteWithChildren = ApiPublicIgRoute._addFileChildren(
  ApiPublicIgRouteChildren,
)

interface ApiPublicWacloudRouteChildren {
  ApiPublicWacloudSalonIdRoute: typeof ApiPublicWacloudSalonIdRoute
}

const ApiPublicWacloudRouteChildren: ApiPublicWacloudRouteChildren = {
  ApiPublicWacloudSalonIdRoute: ApiPublicWacloudSalonIdRoute,
}

const ApiPublicWacloudRouteWithChildren =
  ApiPublicWacloudRoute._addFileChildren(ApiPublicWacloudRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  OnboardingRoute: OnboardingRoute,
  PaymentsRoute: PaymentsRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  BookSlugRoute: BookSlugRoute,
  CatalogSlugRoute: CatalogSlugRoute,
  ManageTokenRoute: ManageTokenRoute,
  ApiInternalTelegramRoute: ApiInternalTelegramRoute,
  ApiPublicIgRoute: ApiPublicIgRouteWithChildren,
  ApiPublicWacloudRoute: ApiPublicWacloudRouteWithChildren,
  PreviewSalonSalonIdRoute: PreviewSalonSalonIdRoute,
  ApiInternalCronJobRoute: ApiInternalCronJobRoute,
  ApiPublicBillingFreedompayRoute: ApiPublicBillingFreedompayRoute,
  ApiPublicIgOauthCallbackRoute: ApiPublicIgOauthCallbackRoute,
  ApiPublicWagupshupTokenRoute: ApiPublicWagupshupTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
