-- WhatsApp Cloud API as a third channel for the AI admin — the official replacement for Green-API.
--
-- WHY: Green-API attaches to WhatsApp as a "linked device" over the WhatsApp Web protocol. That is
-- an unofficial client, and Meta revokes those sessions. The failure mode is not a clean error — the
-- salon simply stops receiving webhooks while our logs stay empty (prod incident 07.08.2026, salon
-- Эркеайым). A booking channel that can vanish overnight is not a product we can sell.
--
-- MIGRATION SAFETY IS THE WHOLE POINT OF THIS FILE. Every column added here defaults to the CURRENT
-- behaviour: wa_provider defaults to 'green_api', wa_cloud_templates_ready defaults to false. After
-- this migration runs, not one salon changes how it sends or receives a single message. A salon
-- moves only when someone flips wa_provider for it explicitly, and flipping it back is the rollback.
--
-- Like the Instagram channel before it (20260805120000), Cloud API conversations REUSE
-- wa_conversations / wa_messages. Everything downstream of the transport — the advisory-lock RPCs,
-- the drain loop, the V4 agent, the admin panel, stats — is keyed on a conversation row and knows
-- nothing about a specific provider.

-- ---------------------------------------------------------------------------
-- 1. The switch itself.
-- ---------------------------------------------------------------------------
-- Deliberately on `salons` rather than `salon_secrets`: this is an operational setting the admin
-- panel reads and displays, not a credential. salon_secrets has no SELECT grant to authenticated.
ALTER TABLE public.salons
  ADD COLUMN IF NOT EXISTS wa_provider text NOT NULL DEFAULT 'green_api';

ALTER TABLE public.salons
  DROP CONSTRAINT IF EXISTS salons_wa_provider_chk;
ALTER TABLE public.salons
  ADD CONSTRAINT salons_wa_provider_chk CHECK (wa_provider IN ('green_api', 'cloud'));

COMMENT ON COLUMN public.salons.wa_provider IS
  'Which WhatsApp transport this salon uses: green_api (default, unofficial linked-device) | cloud (official Meta Cloud API). Decides which webhook route is authoritative and which transport outbound notifications use.';

-- Business-initiated messages (2-hour reminders, reschedule/cancellation notices, owner alerts) fall
-- OUTSIDE Meta's 24-hour customer-service window, where only a pre-approved template may be sent.
-- Template approval takes days and depends on Meta business verification, so a salon can be fully
-- live on Cloud API for inbound conversation long before its templates exist.
--
-- Until this flag is true, a Cloud API salon keeps sending those messages through Green-API (see
-- supabase/functions/send-whatsapp). That is the deliberate hybrid decision recorded in
-- docs/WA-CLOUD-MIGRATION.md (Р1): a salon never silently loses its reminders just because it
-- migrated its inbound channel.
ALTER TABLE public.salons
  ADD COLUMN IF NOT EXISTS wa_cloud_templates_ready boolean NOT NULL DEFAULT false;

COMMENT ON COLUMN public.salons.wa_cloud_templates_ready IS
  'True once this salon has APPROVED Meta message templates. While false, business-initiated messages (reminders, reschedule, cancellation, owner alerts) still go out over Green-API even when wa_provider = cloud.';

-- ---------------------------------------------------------------------------
-- 2. Cloud API credentials, alongside the Green-API and Instagram ones.
-- ---------------------------------------------------------------------------
-- salon_secrets is service-role only (no SELECT grant to authenticated); the admin UI reads and
-- writes it through a server function, exactly as it already does for Green-API and Instagram.
ALTER TABLE public.salon_secrets
  ADD COLUMN IF NOT EXISTS whatsapp_cloud_phone_number_id text,
  ADD COLUMN IF NOT EXISTS whatsapp_cloud_token text,
  ADD COLUMN IF NOT EXISTS whatsapp_cloud_app_secret text,
  ADD COLUMN IF NOT EXISTS whatsapp_cloud_verify_token text,
  ADD COLUMN IF NOT EXISTS whatsapp_cloud_waba_id text,
  ADD COLUMN IF NOT EXISTS whatsapp_cloud_templates jsonb;

COMMENT ON COLUMN public.salon_secrets.whatsapp_cloud_phone_number_id IS
  'Phone number id from the Meta dashboard — NOT the phone number itself. Sends go to /<this id>/messages.';
COMMENT ON COLUMN public.salon_secrets.whatsapp_cloud_token IS
  'Permanent system-user access token with whatsapp_business_messaging. Server-only. Also required as a Bearer on inbound media downloads.';
COMMENT ON COLUMN public.salon_secrets.whatsapp_cloud_app_secret IS
  'Meta app secret. REQUIRED: X-Hub-Signature-256 over the raw body is the only authentication on the inbound POST path (the verify token covers only the GET handshake). A salon without it is refused.';
COMMENT ON COLUMN public.salon_secrets.whatsapp_cloud_verify_token IS
  'Echoed back to Meta during the GET webhook handshake. Generated by us, pasted into the Meta app config.';
COMMENT ON COLUMN public.salon_secrets.whatsapp_cloud_waba_id IS
  'WhatsApp Business Account id. Not needed to send; kept for template management and support tickets.';
COMMENT ON COLUMN public.salon_secrets.whatsapp_cloud_templates IS
  'Approved template names per message kind: {"reminder": {"name": "...", "lang": "ru"}, "reschedule": {...}, "cancellation": {...}, "owner_alert": {...}}. Read only when salons.wa_cloud_templates_ready is true.';

-- ---------------------------------------------------------------------------
-- 3. Channel discriminator: allow 'whatsapp_cloud'.
-- ---------------------------------------------------------------------------
-- The Instagram migration pinned this CHECK to ('whatsapp', 'instagram'), so inserting a Cloud API
-- conversation would fail outright without this. That constraint is the single reason this migration
-- MUST land before any Cloud API code runs.
--
-- Note what is deliberately NOT changed: the conversation's identity stays UNIQUE (salon_id,
-- client_phone). A salon migrating from Green-API to Cloud API keeps the SAME client phone numbers,
-- so each returning client lands on their EXISTING conversation row — history, state and language
-- survive the cutover, and `channel` simply records which transport last carried the thread.
--
-- external_id stays NULL for both WhatsApp flavours: unlike Instagram (where an IGSID is the only
-- identity there is), client_phone already IS the identity here, and leaving it NULL keeps these
-- rows out of the wa_conversations_external_uidx partial index entirely.
ALTER TABLE public.wa_conversations
  DROP CONSTRAINT IF EXISTS wa_conversations_channel_chk;
ALTER TABLE public.wa_conversations
  ADD CONSTRAINT wa_conversations_channel_chk
  CHECK (channel IN ('whatsapp', 'whatsapp_cloud', 'instagram'));

COMMENT ON COLUMN public.wa_conversations.channel IS
  'Transport this conversation arrived on: whatsapp (Green-API) | whatsapp_cloud (official Meta Cloud API) | instagram.';

-- ---------------------------------------------------------------------------
-- 4. Inbound dedup for Cloud API.
-- ---------------------------------------------------------------------------
-- No new index: Meta's wamid goes into the EXISTING wa_messages.green_api_message_id column, which
-- is already guarded by the partial unique index wa_messages_green_id_uniq (salon_id,
-- green_api_message_id) WHERE green_api_message_id IS NOT NULL. Meta redelivers a webhook on any
-- non-200 for up to 36 h, so that guard is what stops a redelivery becoming a second agent turn.
--
-- The column name is now a misnomer for two of the three channels; renaming it would touch the
-- webhook routes, the chat panel, the manual-reply path and the stats queries at a moment when the
-- priority is not breaking a live booking channel. Recorded here rather than done silently.
COMMENT ON COLUMN public.wa_messages.green_api_message_id IS
  'Provider-native message id, used for inbound webhook dedup and outbound delivery-status matching. Green-API: idMessage. Cloud API: wamid. Instagram: message id. Name is historical — it predates the second and third channels.';
