-- Instagram Direct as a second channel for the AI admin.
--
-- Transport is Meta's official Instagram Messaging API (Instagram Login flavour — graph.instagram.com),
-- which costs $0: no per-message fee, no aggregator subscription. The only variable cost of an
-- Instagram conversation is the same Gemini spend a WhatsApp conversation already has.
--
-- Design decision: Instagram conversations REUSE wa_conversations / wa_messages instead of getting
-- their own tables. Everything downstream of the transport — the advisory lock RPCs, the drain loop,
-- the agent state machine, the admin panel, stats — is keyed on a conversation row and knows nothing
-- about WhatsApp specifically. Forking the tables would mean forking all of that too.
--
-- Instagram has no phone number, and wa_conversations.client_phone is NOT NULL + UNIQUE per salon.
-- So an Instagram conversation stores `ig:<IGSID>` there — unique per Instagram user, satisfies the
-- constraint, and is instantly recognisable in the DB. The client's REAL phone (which appointments
-- require: see validate_appointment_phone, 10–15 digits) is asked for by the assistant during the
-- booking and lives in state_data.client_phone. The `channel` column is what code should branch on.

-- 1. Per-salon on/off switch, mirroring salons.whatsapp_enabled.
ALTER TABLE public.salons
  ADD COLUMN IF NOT EXISTS instagram_enabled boolean NOT NULL DEFAULT false;

-- 2. Instagram credentials, alongside the Green-API ones. salon_secrets is service-role only
--    (no SELECT grant to authenticated) — the admin UI reads it through a server function.
ALTER TABLE public.salon_secrets
  ADD COLUMN IF NOT EXISTS instagram_user_id text,
  ADD COLUMN IF NOT EXISTS instagram_token text,
  ADD COLUMN IF NOT EXISTS instagram_app_secret text,
  ADD COLUMN IF NOT EXISTS instagram_verify_token text;

COMMENT ON COLUMN public.salon_secrets.instagram_user_id IS
  'Instagram professional account id (the "entry[].id" Meta sends in webhooks). Used to route a webhook to this salon and as a sanity check.';
COMMENT ON COLUMN public.salon_secrets.instagram_token IS
  'Long-lived Instagram access token with instagram_business_manage_messages. Server-only.';
COMMENT ON COLUMN public.salon_secrets.instagram_app_secret IS
  'Meta app secret. Optional — when set, every webhook POST must carry a valid X-Hub-Signature-256.';
COMMENT ON COLUMN public.salon_secrets.instagram_verify_token IS
  'Echoed back to Meta during the GET webhook handshake. Generated by us, pasted into the Meta app config.';

-- 3. Channel discriminator on the conversation. Existing rows are WhatsApp by definition.
ALTER TABLE public.wa_conversations
  ADD COLUMN IF NOT EXISTS channel text NOT NULL DEFAULT 'whatsapp',
  ADD COLUMN IF NOT EXISTS external_id text;

COMMENT ON COLUMN public.wa_conversations.channel IS
  'Transport this conversation arrived on: whatsapp | instagram.';
COMMENT ON COLUMN public.wa_conversations.external_id IS
  'Channel-native sender id. Instagram: the IGSID (scoped user id) we reply to. NULL for WhatsApp (client_phone is the id there).';

ALTER TABLE public.wa_conversations
  DROP CONSTRAINT IF EXISTS wa_conversations_channel_chk;
ALTER TABLE public.wa_conversations
  ADD CONSTRAINT wa_conversations_channel_chk CHECK (channel IN ('whatsapp', 'instagram'));

-- One conversation per Instagram user per salon. Partial so the WhatsApp rows (external_id NULL)
-- are untouched — their identity stays the existing UNIQUE (salon_id, client_phone).
CREATE UNIQUE INDEX IF NOT EXISTS wa_conversations_external_uidx
  ON public.wa_conversations (salon_id, channel, external_id)
  WHERE external_id IS NOT NULL;

-- The admin panel lists conversations per channel, newest first.
CREATE INDEX IF NOT EXISTS wa_conversations_channel_idx
  ON public.wa_conversations (salon_id, channel, last_message_at DESC);
